name: Release

on:
  push:

  pull_request:
    branches:
      - master

  release:
    types: [published]

  workflow_dispatch:
    inputs:
      new-version:
        description: New version to be published, overrides tag
        required: true
        type: string

      npm-tag:
        description: NPM tag
        required: true
        default: latest
        type: choice
        options:
          - latest
          - next

jobs:
  publish:
    runs-on: ubuntu-slim

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use Node.js latest
        uses: actions/setup-node@v7
        with:
          node-version: latest
          token: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Pack package
        run: npm pack
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        with:
          name: package
          path: "*.tgz"

      - name: Publish to NPM
        run: |
          npm version --allow-same-version --no-git-tag-version $VERSION
          npm stage publish --provenance --tag $TAG
        if: ${{ !env.ACT && (github.event_name == 'release' || github.event_name == 'workflow_dispatch') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ inputs.npm-tag || 'latest' }}
          VERSION: ${{ inputs.new-version || github.ref_name }}
